version: '2.1'

services:
  db:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
        MYSQL_USER: root
        MYSQL_DATABASE: inter_2
    restart: always
  interviewtask-app:
    image: koondzioo/springboot-interview-app:1.2.0
    container_name: springboot-interview-app
    depends_on:
      - db
      - hub
    ports:
      - 8081:8080
    environment:
      IMG_ROOT: /app/files
    volumes:
      - ./data:/app/files
    links:
      - db
      - hub
  chrome:
    image: selenium/node-chrome:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    links:
      - hub
  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"
